apiVersion: org.citrusframework.yaks/v1alpha1
kind: Test
metadata:
  name: example-test
spec:
  source:
    name: simple.feature
    language: feature
    content: |-
      Feature: integration runs

        Scenario:
          Given integration simple is running
          Then integration simple should print Hello Camel
