kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: yaks-viewer
  labels:
    org.citrusframework.yaks/app: "yaks"
subjects:
- kind: ServiceAccount
  name: yaks-viewer
roleRef:
  kind: Role
  name: yaks-viewer
  apiGroup: rbac.authorization.k8s.io
