config:
  runtime:
    env:
      - name: CITRUS_DEFAULT_MESSAGE_TYPE
        value: PLAINTEXT
    settings:
      dependencies:
        - groupId: org.postgresql
          artifactId: postgresql
          version: "@postgresql.version@"